database:
  url: http://localhost:8050

task:
  url: http://localhost:8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 11111111
    driver-class-name: org.postgresql.Driver
